### ISSUE TITLE
Add AssignmentInCondition check

### ISSUE THREAD

**Issue by Halama** [keboola/phpcs-standard#14]
https://github.com/slevomat/coding-standard/tree/608b4b9b38c2a13b7941397bda257db3f08b4380#slevomatcodingstandardcontrolstructuresassignmentincondition

https://github.com/keboola/connection/pull/1488#discussion_r209968073

**Comment by ujovlado** [comment]
https://keboola.slack.com/archives/C9FEAHW7N/p1534259626000100

co toto?
```php
if (($value = getValue()) !== null) {
  // do something with $value
}
```

**Comment by pivnicek** [comment]
asi nejde.  tam maji jen `Assignment in while loop condition is specifically allowed because it's commonly used.`

**Comment by ujovlado** [comment]
yep, so this will be allowed:

```php
while (($value = getValue()) !== null) {
  // do something with $value
}
``` 
and this not:

```php
if (($value = getValue()) !== null) {
  // do something with $value
}
```

what a mess ...

**Comment by odinuv** [comment]
mess would be rewriting the while without assignment

**Comment by tomasfejfar** [comment]
Změna byla přijata. Otestuju a mergnu.
