### ISSUE TITLE
Check of file pointer existence by assertFileExists is not enough

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/phpcs-standard#26]
Nešlo by tohle doladit?
![image](https://user-images.githubusercontent.com/215660/58626163-6c1c9180-82d4-11e9-857c-ec9243562023.png)

Psát to takhle je takový dost nadbtečný, ne?
![image](https://user-images.githubusercontent.com/215660/58626219-8a828d00-82d4-11e9-83e1-899e29310d10.png)

**Comment by tomasfejfar** [comment]
Nejjednodušší je použít https://github.com/keboola/php-component/blob/master/src/JsonHelper.php který tímhle vůbec netrpí...

**Comment by tomasfejfar** [comment]
Ale takhle chyba je z PhpStanu, ne?

**Comment by JakubMatejka** [comment]
Aha, ok. Jj. z phpstanu
