### ISSUE TITLE
Checks the length of all lines in a file?

### ISSUE THREAD

**Issue by Halama** [keboola/phpcs-standard#6]
Přidat [LineLengthSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/Files/LineLengthSniff.php)  povolující max `120` znaků?

**Comment by tomasfejfar** [comment]
Vykopnutá diskuse v #best-practices a pokud nikdo nebude nic mít, tak to tam přidám. Pro extrémní výjimky [se dá na pár řádků sniff vypnout](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file).

**Comment by tomasfejfar** [comment]
Ref.: https://keboola.slack.com/archives/C9FEAHW7N/p1523535579000069
